# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5974979a36ed3c983d38629061a0a8cb5d1fce2aa2d6088311781b6bbe580d272c828ec6300e5cd84eea6e5e604119d8f4f1d00d53f1f65e6f92eeedb43705b5

test:
  secret_key_base: 007607ab0a2121250e7583902b8fb9a5b86dacb80d83420ba027e49076b0032cf4a52d9c6f491c6d1bdb84c97eb810d6831308a59c14e39522c706a9c9c0b5ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
